# Generated by Django 5.1.3 on 2024-12-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('url', models.URLField(default='https://github.com/asilbek-ismoilov?tab=repositories')),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=70)),
                ('size', models.CharField(default='col-lg-5', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='app.portfoliocategory')),
            ],
        ),
    ]
